name: Application Test and Release Workflow

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build docker image and push it to docker hub
      env:
        DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        ls -l
        echo 'Docker login'
        docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
        echo 'Running build...'
        docker build . -t enricmartos/spottern-landing-page:latest
        echo 'Pushing image...'
        docker push enricmartos/spottern-landing-page:latest
        echo 'Done!..'
        echo 'Pushing image...'
        docker push enricmartos/spottern-landing-page:latest
        echo 'Done!'
        docker build -t spottern-landing-page .
    - name: deploy to heroku
    - uses: actions/checkout@v1
      env:
        HEROKU_APP_NAME: spottern-landing-page
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
    - run: |+
        cat >~/.netrc <<EOF
        machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
        machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
        EOF
    - run: heroku git:remote -a $(basename ${{ github.repository}} )
    - run: git push heroku HEAD:refs/heads/master
