name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        ls -l
        echo 'Docker login'
        docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
        echo 'Running build...'
        docker build . -t enricmartos/spottern-landing-page:latest
        echo 'Pushing image...'
        docker push enricmartos/spottern-landing-page:latest
        echo 'Done!..'
        echo 'Pushing image...'
        docker push enricmartos/spottern-landing-page:latest
        echo 'Done!'
        docker build -t spottern-landing-page .
