name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build docker image and push it to docker hub
      env:
        DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        ls -l
        echo 'Docker login'
        docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
        echo 'Running build...'
        docker build . -t enricmartos/spottern-landing-page:latest
        echo 'Pushing image...'
        docker push enricmartos/spottern-landing-page:latest
        echo 'Done!..'
        echo 'Pushing image...'
        docker push enricmartos/spottern-landing-page:latest
        echo 'Done!'
        docker build -t spottern-landing-page .
    - name: push docker image to heroku
      env:
        HEROKU: ${{ secrets.HEROKU }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo 'Set up Heroku Oauth based on the api key'
        echo "machine api.heroku.com  login $HEROKU  password $HEROKU_API_KEY machine git.heroku.com  login $HEROKU  password $HEROKU_API_KEY" > ~/.netrc
        cat ~/.netrc
        echo 'Debug pushing image to Heroku...'
        echo $PWD
        git remote add heroku https://git.heroku.com/spottern-landing-page.git
        git remote -v
        git config user.email "enric.martos@gmail.com"
        git add .
        git commit -m "fix pushing to heroku git repo"
        git push heroku master
